---
# Pre-install: remove existing Zabbix repository on RPM-based systems

- name: Remove existing Zabbix repository package
  ansible.builtin.dnf:
    name: zabbix-release
    state: absent
  tags:
    - zabbix-agent-remove
    - repo
