---
# Pre-install: remove existing Zabbix repository on SUSE systems

- name: Remove existing Zabbix repository package
  community.general.zypper:
    name: zabbix-release
    state: absent
  tags:
    - zabbix-agent-remove
    - repo
