---
# Tasks for installing Zabbix Agent 2 on SUSE/SLES

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: rpm

- name: Download Zabbix repository package
  ansible.builtin.get_url:
    url: >-
      https://repo.zabbix.com/zabbix/{{ zabbix_agent_version
      }}/sles/{{ ansible_facts['distribution_major_version'] }}/{{
      ansible_facts['architecture'] }}/zabbix-release-latest-{{
      zabbix_agent_version }}.sles{{
      ansible_facts['distribution_major_version'] }}.noarch.rpm
    dest: /tmp/zabbix-release.rpm
    mode: "0644"
  when: "'zabbix-release' not in ansible_facts.packages"
  tags:
    - zabbix-agent-repo
    - repo

- name: Install Zabbix repository on SUSE
  community.general.zypper:
    name: /tmp/zabbix-release.rpm
    state: present
    disable_gpg_check: true
  when: "'zabbix-release' not in ansible_facts.packages"
  tags:
    - zabbix-agent-repo
    - repo

- name: Remove temporary repository package
  ansible.builtin.file:
    path: /tmp/zabbix-release.rpm
    state: absent
  when: "'zabbix-release' not in ansible_facts.packages"

- name: Refresh Zabbix Official Repository
  ansible.builtin.command: zypper --gpg-auto-import-keys refresh 'Zabbix Official Repository'
  changed_when: false
  check_mode: false
  when: "'zabbix-release' not in ansible_facts.packages"
  tags:
    - zabbix-agent-upgrade-repo

- name: Install Zabbix Agent 2 and plugins
  community.general.zypper:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present
    update_cache: true
  tags:
    - zabbix-agent-install
    - install-agent

- name: Configure Zabbix Agent 2
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    mode: "0644"
  notify: Restart zabbix-agent2
  tags:
    - zabbix-agent-conf
    - conf

- name: Enable and start Zabbix Agent 2 service
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: true
    state: started
  tags:
    - zabbix-enable
    - service
